language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: Vor73aKmZahERsv/kWZ9SEc50OLMbrHFMApbVRPCwA4HQHplrfuod2Gx2lyfxBlWyahF5oh7Z1rvp+6pBoOi8by4/YJ1wZd0PFFYBH7HN5RkhjitYbdnlJnEt+cm4x11rLtK9xR75LHvQR4AczWnAcdhcINW5ZXplsXbBIvOj8wHtKqgNWcFKBPD/PQ57lYC7PET1/WCXBb3mh8cNHKzMHdNvJ1dRyzOl5BQtvztnDeMMJlw6q28z68ZRRlbXZVxeGpTzpdWbQQ2NdxlaA87fANUVXQmXKJklcpYTyVpmIoRaOQTRnmrjveG666ZBuPkv3xna5tKUhYAazijRWwDQswudTMy4EoaRpqRlkPILfdS2Q7OEGsFWo3a7YbUjvirflx+JsO5ycecPHvr4qrZu2Z8KJ/+lVd0Gg+PRobupoSeFO9trps5C2JyZBEreVLjv6Mu2jQ5KwQlwe5OpYHxJofZGjxCD0buAE7aK1ORI6rBvVEE/5LdM20mT8/2dQBR9+FvoBQ7ItEqIwdRP/4Ys+6xk5VBbfhO+QsWRqldq7SWe6PLgho7ZmqtfKxvYNdNMeg8mgBeudz6ZVtg06mcM6NK92hKT13TTPII56SnZq2qqIMwoLsgfjDSxINQERWz14CToHz0akWYSBwTPGdwryv83+GqDCdqFqScQ+U8nf0=
  app: calm-meadow-29295
  on:
    repo: Doonyby/bcskibuddy
