language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: HNp4LH72IoVM4ISTpo3DwihykN6stzPepIzhRTQEDnsh/vmaTHBNjUu8GvM5PXun8KP6OeNGlApsW1wQVE/PnDPkr0GPr6DP1L9YYlDEpKuNm1wpLj4MfjWfciaV4WK5W/WjWW6zsuji3OJxA05KPLK0vd0uaw4zKZUoNZUO7+hnCkMU+320exKERnUO/oOKaRj4vNMz03BuENvDuP+tmSP35+GyxPGx7GHpDbcxnpbZAjmfLKplsEMDrSWYWAZdNh1teuLiKrWmyv63YhJ2FtIlOKFCN/oLdPZD1XA+T9KnnTje2GMMuoY9OeeWccAwTmD55z/pr8DunVHbj8R6rMOn3WDjax07FJKFTScLAtWzS5fuk4zm1Uttcmzdr44VPLaetpBYKgKgMcuthVJpcDwbUtTNht1Z685jpM8joNllBdKcoKTiksHXhY+NxRY2FjI8GAuKEyto/zFHe+qV2RJdabAzQuNyCWbESjis9N5g2c0ih5JjiUODIQhR/FzmESULq64WgvBCJyqd9dhdz2/7KJkTRDi+uiO2xhxdbCiGHySgnLoGJWF0N65R7D0jL4YjdJTl85VYxbeb/CDeBgkwdmDMV4hx6NLBidFKY3DB5jOmQxuSb0J8KExeBdAM9wNPyKc0fbgmnLaaudoW/sUlAaU3nAdtpxPKDcaPXfU=
  app: calm-meadow-29295
  on:
    repo: Doonyby/bcskibuddy
